@startuml
interface IVoltage5V
Client ..> Phone
Client ..> VoltageAdapter
Phone ..> IVoltage5V
Voltage220V  <|-- VoltageAdapter
IVoltage5V <|.. VoltageAdapter

Phone : charging():void
IVoltage5V : output5V():void
Voltage220V : output220V():void
VoltageAdapter : output5V:int
@enduml